name: bip39
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.6
homepage: https://github.com/anicdh/bip39
author: anicdh <email@example.com>

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  pointycastle: ^3.9.1
  hex: ^0.2.0
  crypto: ^3.0.3
dev_dependencies:
  test: ^1.0.0
